# TODO: this is temporary, this value is not real, replace with vault
# injection and read from in-memory volume for better security
apiVersion: v1
kind: Secret
metadata:
  name: api-key
type: Opaque
stringData:
  value: temp-api-key
